"""gallery is added in the rest

Revision ID: 1ed577d5f7d4
Revises: 1040da39e474
Create Date: 2025-10-15 22:11:08.251320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ed577d5f7d4'
down_revision = '1040da39e474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gallery', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_column('gallery')

    # ### end Alembic commands ###
